apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2723830675458453208
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-2/context/2723830675458453208
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2723830675458453208"
  targetNamespace: default
status: {}
