apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust4572662868150298792
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-2/context/4572662868150298792
  prune: true
  sourceRef:
    kind: GitRepository
    name: "4572662868150298792"
  targetNamespace: default
status: {}
