apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust7918590170884202495
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+huba/context/7918590170884202495
  prune: true
  sourceRef:
    kind: GitRepository
    name: "7918590170884202495"
  targetNamespace: default
status: {}
