apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "1130324341910122417"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Airren/pull-mode-1.24
status: {}
