apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust5338990401645358451
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/5338990401645358451
  prune: true
  sourceRef:
    kind: GitRepository
    name: "5338990401645358451"
  targetNamespace: default
status: {}
