apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust7707203923077848941
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/7707203923077848941
  prune: true
  sourceRef:
    kind: GitRepository
    name: "7707203923077848941"
  targetNamespace: default
status: {}
