apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6614186454501605885
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/6614186454501605885
  prune: true
  sourceRef:
    kind: GitRepository
    name: "6614186454501605885"
  targetNamespace: default
status: {}
